CREATE DATABASE customer_Shoping_Behaviour_db;
USE customer_Shoping_Behaviour_db;
SELECT * FROM customer_data;

-- Q1. What is the total revenue generated by male vs. female customers?


SELECT gender , SUM(purchase_amount) as revenue
from customer_data
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
from customer_data
where discount_applied = 'yes' and purchase_amount >= (SELECT AVG(purchase_amount) from customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased , ROUND(AVG(review_rating),2) as "Average Product Rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS "Average Purchase Amount"
FROM customer_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg(purchase_amount) DESC;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status , COUNT(customer_id) AS "Total_Customers" , ROUND(AVG(purchase_amount),2) AS "Average_Spend", ROUND(SUM(purchase_amount),2) as "Total_Revenue"
FROM customer_data
GROUP BY subscription_status
ORDER By Total_Revenue, Average_Spend DESC;

SELECT * FROM customer_data;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100 * SUM( CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*),2) as discount_rate
from customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

 WITH customer_type as (
 SELECT customer_id, previous_purchases,
 CASE WHEN previous_purchases = 1 THEN 'NEW'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
        END AS customer_segment
from customer_data
)
 SELECT customer_segment , COUNT(*) as "Number of customers"
 FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer_data
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status;


-- Q10. What is the revenue contribution of each age group?

SELECT * FROM customer_data;
SELECT age_group, SUM(purchase_amount) as "revenue_contribution"
FROM customer_data
GROUP BY age_group
ORDER BY revenue_contribution DESC;


ALTER USER 'root'@'localhost' 
IDENTIFIED WITH mysql_native_password 
BY 'Deependra@123';

FLUSH PRIVILEGES;

SELECT VERSION();

CREATE USER 'powerbi_user'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';

GRANT ALL PRIVILEGES ON customer_Shoping_Behaviour_db.* TO 'powerbi_user'@'localhost';

FLUSH PRIVILEGES;